### ISSUE TITLE
Some beanValidations dont work when updating an entity

### ISSUE THREAD

**Issue by pierre-duchesne** [resthub/resthub-spring-stack#177] opened 2013-01-25 16:10 UTC
For instance

```
@NotNull
@Size(min = 1, max=20)
@Getter @Setter
private String firstname;
```

The notNullvalidation is checked when persisting & updating (because the result of this beanValidation is a constraint directly on the database)

The Size validation is not checked when updating an entity.

Have you some advices to change this behavior ?

**Comment by bmeurant** [comment] 2014-01-23 00:56
Is this still an active issue ? I cannot reproduce ...

**Comment by bmeurant** [comment] 2014-01-24 14:10
Seems to be a missing @Valid BeanValidation annotation missing to force validation of nested entities.

I close this one.

**Closed as completed by bmeurant** 2014-01-24 14:10 UTC
